### ISSUE TITLE
Error message: Unknown option --citeproc. 

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/leanbuild#5]
I've updated the Docker image to have the most recent build of the leanbuild package and I am getting this error when I run 
```
leanbuild::bookdown_to_leanpub()
```
I'm running this from the top of this repo: https://github.com/jhudsl/DaSL_Course_Template_Bookdown
Full error message: 
```
Unknown option --citeproc.
Unknown option --citeproc.
Try pandoc --help for more information.
Error: pandoc document conversion failed with error 2
```

**Comment by cansavvy** [comment]
This line is where the error comes from: 
https://github.com/jhudsl/leanbuild/blob/6c3699c1e5590bc1f18cc3261d3a944ff4c223f4/R/bookdown_to_leanpub.R#L125

Just not sure how to fix it yet.

**Comment by cansavvy** [comment]
This might be fixed if we upgrade to https://github.com/rstudio/rmarkdown/releases

**Comment by carriewright11** [comment]
wait I had this! let me check my notes!

**Comment by carriewright11** [comment]
nevermind I see you fixed it

**Comment by carriewright11** [comment]
sorry I forgot about this detail...

**Comment by cansavvy** [comment]
Okay. I didn't entirely fix it but we are part of the way there. There were two warnings and now there's one! lol.

**Comment by cansavvy** [comment]
So if you still have something helpful in your notes, that would be superb!

**Comment by cansavvy** [comment]
Oh I see there's another instance of --citeproc I missed. https://github.com/jhudsl/leanbuild/blob/335a8df3bb5da09c16021feb880a6dc1f70f8809/R/bookdown_to_leanpub.R#L127

Will file another PR

**Comment by carriewright11** [comment]
Ok good! I think I updated RStudio and also John made some updates to the package and I pulled those

**Comment by cansavvy** [comment]
> Ok good! I think I updated RStudio and also John made some updates to the package and I pulled those

I rebuilt the docker image with the latest leanbuild and still get this error.

**Comment by cansavvy** [comment]
What version of rmarkdown are you using?

**Comment by carriewright11** [comment]
did you try updating RStudio? it will  update your pandoc

**Comment by carriewright11** [comment]
2.9.5

**Comment by carriewright11** [comment]
I think it ultimately had to do with having the correct pandoc version - which you can do manually but RStudio usually picks one that isn't quite as recent

**Comment by cansavvy** [comment]
> I think it ultimately had to do with having the correct pandoc version - which you can do manually but RStudio usually picks one that isn't quite as recent

What version of pandoc do you have locally? The docker image is using pandoc 2.7.3

**Comment by carriewright11** [comment]
2.11.4

**Comment by carriewright11** [comment]
that might be it...

**Comment by cansavvy** [comment]
That's an easy problem to solve. I'm going to try that now.

**Comment by cansavvy** [comment]
> That's an easy problem to solve. 

Should have known better than to call it "easy". It's turning out to be a more tangled problem than I thought.

**Comment by carriewright11** [comment]
oh dear :(

**Comment by cansavvy** [comment]
Thank goodness this is done. Turned out to be a nasty dependency entanglements. See Updating Pandoc in the docker image jhudsl/DaSL_Course_Template_Bookdown#136 for more info.
