### ISSUE TITLE
Look into how tricky it is to automagically make all links be in a new tab

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/leanbuild#55]
```
I wonder if we should both set our links to all be a new tab? - kinda difficult to figure out where you were- but maybe it is good to give people the option to right click
```

**Comment by carriewright11** [comment]
I have used this in other rmarkdowns... 
  
<base target="_blank"/>  
<div id="google_translate_element"></div>

<script type="text/javascript" src='//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit'></script>

<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
}
</script>

I think it is probably ok to leave this for later... oh lol you are simultaneously removing the tag :P

**Comment by carriewright11** [comment]
In a way I think it is ok to leave as is anyway... cause people have the option if the right click... otherwise they dont have the option
