### ISSUE TITLE
Images are smaller than they used to be

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/leanbuild#64]
We think fullbleed argument got changed resulting in smaller images on Leanpub from our slides.

Old:
![Screen Shot 2021-09-24 at 2 55 38 PM](https://user-images.githubusercontent.com/23014755/134726304-8f6af232-4bd8-45f7-a05e-bb4b676d3c63.png)

New:
![Screen Shot 2021-09-24 at 2 55 26 PM](https://user-images.githubusercontent.com/23014755/134726333-023ac521-67a7-4338-a6f6-8bc7cef101a1.png)

**Comment by carriewright11** [comment]
I think this part (highlighted as code) might just need to be added back to the build image function:

This is the old version:
build_image = function(src, ..., caption = NULL, embed = NULL,
                       fullbleed = FALSE,
                       remove_resources_start = TRUE) {
  if (remove_resources_start) {
    src = gsub("^resources/", "", src)
  }

  myenv = list(...,
               caption = caption,
               embed = embed,
               src = src)
  myenv = as.environment(myenv)
  x = c('alt: "{alt}",',
        'height: "{height}",',
        'width: "{width}",',
        'align: "{align}"',
        'embed: "{embed}"'
  )
  if (is.null(fullbleed) ||
      length(fullbleed) == 0 ||
      fullbleed == "" ||
      is.na(fullbleed)) {
    fullbleed = FALSE
  }
```
  x = sapply(x, glue::glue, .envir = myenv)
  x = unlist(sapply(x, as.character))
  x = c(x, if (fullbleed) 'fullbleed: true')
  x = paste(x, collapse = " ")
  x = paste0("{", x, "}\n")
  x = paste0(x, paste0("![", myenv$caption, "](", myenv$src, ")"))
  x
```
}

**Comment by carriewright11** [comment]
or we could just decide to always do fullbleed = TRUE... but that seems like it might not work for Candace's icons that are really large already - but important for people to be able to see large enough versions of images that are more involved

**Comment by carriewright11** [comment]
checking further in my old files with big images in Leanpub... images looked like this:
{alt: "Learning Objectives:1)Know why diversity has been shown to be beneficial 2)Recognition about how certain groups are underrepresented in computational biology both as research participants and researchers 3)Research strategies to better support health equity 4) Know management strategies to better support a more diverse team of employees, mentees, and collaborators", width: "100%", align: "middle"}

Now it looks like this with the current leanbuild and looks smaller in leanpub.
{alt: "Learning Objectives:1)Know why diversity has been shown to be beneficial 2)Recognition about how certain groups are underrepresented in computational biology both as research participants and researchers 3)Research strategies to better support health equity 4) Know management strategies to better support a more diverse team of employees, mentees, and collaborators", width: "100%", align: "middle",}

hmmm so otherwise this could be about the extra comma?

**Comment by carriewright11** [comment]
I am going to try manually deleting the comma to test this.

**Comment by carriewright11** [comment]
OK! commas are fine, order is fine. But the period at the end is not fine.

**Comment by cansavvy** [comment]
Looks like this is fixed? https://leanpub.com/courses/jhu/jhudsl_course_template/read/preview/3?preview=true#leanpub-auto-topic-of-section
