### ISSUE TITLE
Noticing a period after images in Leanpub

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/leanbuild#65]
![Screen Shot 2021-09-24 at 3 02 47 PM](https://user-images.githubusercontent.com/23014755/134727514-5b26ebe5-b3ac-4aee-9e32-d71d4320cf8b.png)

**Comment by carriewright11** [comment]
This disrupts video centering and making images smaller

**Comment by cansavvy** [comment]
Looks like this fixed #64 !
