### ISSUE TITLE
Noticing images get left aligned if no space between code chunk for image and text before it

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/leanbuild#66]
[](url
![Screen Shot 2021-09-24 at 3 02 47 PM](https://user-images.githubusercontent.com/23014755/134727580-67a57bb9-8544-4d97-b407-fa7f5bcf8e78.png)
)

**Comment by carriewright11** [comment]
This might be resolved when we change image size

**Comment by carriewright11** [comment]
This issue should be resolved when remove the extra period.

**Comment by cansavvy** [comment]
Is this also resolved? https://leanpub.com/courses/jhu/jhudsl_course_template/read/preview/3?preview=true#leanpub-auto-topic-of-section
