### ISSUE TITLE
Noticing videos are left aligned

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/leanbuild#67]
Trying to see if modifying the original Rmd to specify that it should be centered fixes this... or maybe the attribute for centering got dropped in the bookdown_to_leanpub() function.

**Comment by carriewright11** [comment]
This is what videos look like currently in the md for Leanpub after leanbuild:
{height: "400px", width: "100%", align: "middle", type: "video", poster: "http://img.youtube.com/vi/VOCYL-FNbr0/mqdefault.jpg",} Click on the lower right corner to expand the screen.

This is what it looked like with my old script that was middle aligned:
{type: video, poster: 'http://img.youtube.com/vi/VOCYL-FNbr0/mqdefault.jpg',height: "400px", width: "100%", align: "middle"}
![Click lower right corner of video to expand](https://www.youtube.com/watch?v=ViDtnfQ9FHc)

I wonder if the order is important...(I vaguely remember that I thought it was when testing for my script)

**Comment by cansavvy** [comment]
If you can determine a positive control for me, then I can go in and make leanbuild follow that example. OR if it's just that Leanpub is acting up again, we can mail them again.

**Comment by carriewright11** [comment]
Thanks! I don't think it is that leanpub is acting up because my old files (rendered from my old scripts) from a couple of weeks ago are centered. 

This should work I believe as a positive control, as it is what is currently published for Leanpub for my course.

{height: "400px", width: "100%", align: "middle", type: "video", poster: "http://img.youtube.com/vi/VOCYL-FNbr0/mqdefault.jpg",} Click on the lower right corner to expand the screen.

Here is an example of an old file that is currently the version published on Leanpub: https://github.com/jhudsl/ITCR_Cancer_Research_Leadership_Leanpub/blob/main/manuscript/leanpub_ready_06-management_tools_embed_ready.md

And the code for the video in the below image looks like this:
{type: video, poster: 'http://img.youtube.com/vi/VOCYL-FNbr0/mqdefault.jpg',height: "400px", width: "100%", align: "middle"} Click lower right corner of video to expand


![Screen Shot 2021-09-27 at 3 47 31 PM](https://user-images.githubusercontent.com/23014755/134975112-b097b944-b19c-493d-b64e-451373dab503.png)

from my testing I recall it being important that `type:video` came first. I never tried doing `poster:` somewhere else...

**Comment by carriewright11** [comment]
unless maybe this has to do with the extra comma?

**Comment by carriewright11** [comment]
I am going to try manually deleting the comma to test this.

**Comment by cansavvy** [comment]
Yes if the comma throws it off, that definitely bumps that problem up on the priority list.

**Comment by carriewright11** [comment]
this issue should be resolved when remove the extra period at the end

**Comment by cansavvy** [comment]
I think this is also resolved!
