### ISSUE TITLE
Add check that quizzes exist

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/leanbuild#81]
add check for quizzes based on  #79

**Comment by cansavvy** [comment]
I don't think we need this necessarily. I could see someone wanting to publish on Leanpub and not have quizzes. Or not have quizzes yet. And not having quizzes won't make this fail (I don't think).

**Comment by carriewright11** [comment]
hmmm without quizzes though... idk if they can do a certificate...

**Comment by carriewright11** [comment]
(for ITCR I mean..) but yes useful still for making books I think

**Comment by cansavvy** [comment]
By default it looks for quizzes and will warn them if it's not found. But if someone doesn't want to have quizzes they can say `quiz_dir = NULL` and it will skip that. I think this covers these use cases in a reasonable manner if you are okay with that.
